apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: marketplace-database-data
spec:
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 10Gi

---

apiVersion: v1
kind: Service
metadata:
  name: markeplace-database
spec:
  clusterIP: None
  ports:
  - port: 1433
    targetPort: 1433
  selector:
    database: marketplace

---

apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: marketplace-database
spec:
  serviceName: marketplace-database
  selector:
    matchLabels:
      database: marketplace
  template:
    metadata:
      labels:
        database: marketplace
        system: database
    spec:
      terminationGracePeriodSeconds: 60
      containers:
      - name: marketplace-database
        image: mcr.microsoft.com/mssql/server:2019-latest
        imagePullPolicy: IfNotPresent
        ports:
        - containerPort: 1433
        resources:
          limits:
            memory: "2Gi"
            cpu: "1000m"
        env:
        - name: ACCEPT_EULA
          value: "Y"
        - name: SA_PASSWORD
          valueFrom:
            secretKeyRef:
              name: environment-secrets 
              key: marketplace-database-sa-password
        volumeMounts:
        - name: marketplace-database-data
          mountPath: /var/opt/mssql
      volumes:
        - name: marketplace-database-data
          persistentVolumeClaim:
            claimName: marketplace-database-data